import {
  Bars3BottomLeftIcon,
  HomeModernIcon,
  ReceiptPercentIcon,
  TruckIcon,
} from "@heroicons/react/24/outline";

export const catalogConfigs = {
  cause: {
    type: "cause",
    plural: "Causali",
    singular: "causale",
    newLabel: "Nuova causale",
    article: "la causale",
    icon: Bars3BottomLeftIcon,
    settingsPath: "/settings/causes",
    description: "Gestisci le causali selezionabili durante la registrazione degli accrediti.",
    emptyText: "Nessuna causale registrata",
    registeredLabel: "Causali registrate",
    fields: [
      { name: "name", label: "Nome causale", required: true, placeholder: "Es. Compenso professionale" },
      { name: "description", label: "Descrizione", type: "textarea", full: true, placeholder: "Nota facoltativa sulla causale" },
    ],
    summary: (item) => item.description || "Disponibile per la registrazione degli accrediti",
  },
  tax: {
    type: "tax",
    plural: "Tasse",
    singular: "tassa",
    newLabel: "Nuova tassa",
    article: "la tassa",
    icon: ReceiptPercentIcon,
    settingsPath: "/settings/taxes",
    detailBasePath: "/taxes",
    description: "Gestisci imposte, tributi e relative scadenze.",
    emptyText: "Nessuna tassa registrata",
    registeredLabel: "Tasse registrate",
    fields: [
      { name: "name", label: "Nome tassa", required: true, placeholder: "Es. IMU" },
      {
        name: "cadence",
        label: "Cadenza pagamento",
        type: "select",
        required: true,
        defaultValue: "annual",
        options: [
          ["monthly", "Mensile"],
          ["quarterly", "Trimestrale"],
          ["semiannual", "Semestrale"],
          ["annual", "Annuale"],
          ["one-time", "Una tantum"],
        ],
      },
      { name: "nextDueDate", label: "Prossima scadenza", type: "date" },
      { name: "notes", label: "Note", type: "textarea", full: true, placeholder: "Informazioni facoltative" },
    ],
    summary: (item) => {
      const cadence = {
        monthly: "Mensile",
        quarterly: "Trimestrale",
        semiannual: "Semestrale",
        annual: "Annuale",
        "one-time": "Una tantum",
      }[item.cadence];
      return [cadence, item.nextDueDate ? `Scadenza ${item.nextDueDate}` : null].filter(Boolean).join(" · ");
    },
  },
  property: {
    type: "property",
    plural: "Immobili",
    singular: "immobile",
    newLabel: "Nuovo immobile",
    article: "l'immobile",
    icon: HomeModernIcon,
    settingsPath: "/settings/properties",
    detailBasePath: "/properties",
    description: "Gestisci gli immobili e i relativi riferimenti.",
    emptyText: "Nessun immobile registrato",
    registeredLabel: "Immobili registrati",
    fields: [
      { name: "name", label: "Nome immobile", required: true, placeholder: "Es. Casa Via Pio X" },
      { name: "address", label: "Indirizzo", required: true, placeholder: "Via e numero civico" },
      { name: "city", label: "Città", placeholder: "Comune" },
      { name: "postalCode", label: "CAP", placeholder: "Es. 90100" },
      { name: "cadastralReference", label: "Riferimento catastale", full: true, placeholder: "Foglio, particella, subalterno" },
      { name: "notes", label: "Note", type: "textarea", full: true, placeholder: "Informazioni facoltative" },
    ],
    summary: (item) => [item.address, item.city].filter(Boolean).join(" · "),
  },
  vehicle: {
    type: "vehicle",
    plural: "Veicoli",
    singular: "veicolo",
    newLabel: "Nuovo veicolo",
    article: "il veicolo",
    icon: TruckIcon,
    settingsPath: "/settings/vehicles",
    detailBasePath: "/vehicles",
    description: "Gestisci veicoli, targhe e dati identificativi.",
    emptyText: "Nessun veicolo registrato",
    registeredLabel: "Veicoli registrati",
    fields: [
      { name: "name", label: "Nome nella sidebar", required: true, placeholder: "Es. Peugeot 3008" },
      { name: "make", label: "Marca", required: true, placeholder: "Es. Peugeot" },
      { name: "model", label: "Modello", required: true, placeholder: "Es. 3008" },
      { name: "plate", label: "Targa", required: true, placeholder: "Es. AB123CD" },
      { name: "year", label: "Anno", type: "number", min: 1900, max: 2100, placeholder: "Es. 2024" },
      { name: "notes", label: "Note", type: "textarea", full: true, placeholder: "Informazioni facoltative" },
    ],
    summary: (item) => [item.make, item.model, item.plate].filter(Boolean).join(" · "),
  },
};
